name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test-macos:
    name: Test for macOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1'
    
    - name: Cache Swift Package Manager
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Build and Test
      run: |
        set -o pipefail
        xcodebuild clean build test \
          -scheme Mithril \
          -destination 'platform=macOS' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          ONLY_ACTIVE_ARCH=NO \
          | xcpretty



  swiftlint:
    name: SwiftLint
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: swiftlint lint --strict

  package-validation:
    name: Package Validation
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Validate Swift Package
      run: swift package resolve && swift build

  fastlane:
    name: Fastlane
    runs-on: macos-latest
    needs: [test-macos, swiftlint, package-validation]
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    
    - name: Install Fastlane
      run: gem install fastlane
    
    - name: Run Fastlane
      run: fastlane ios ci
      env:
        FASTLANE_SKIP_UPDATE_CHECK: true
        FASTLANE_HIDE_CHANGELOG: true